# A primer on Numpy Multiplication

In [2]:
import numpy as np

In [11]:
print('================')
print('a*b')
print('')
a = np.ceil(10*np.random.randn(3,))
b= np.ceil(10*np.random.randn(3,))
print(a)
print(b)
print(a*b)
print('')
a = np.ceil(10*np.random.randn(3,1))
b= np.ceil(10*np.random.randn(3,1))
print(a)
print(b)
print(a*b)
print('')
a = np.ceil(10*np.random.randn(1,3))
b= np.ceil(10*np.random.randn(3,1))
print(a)
print(b)
print(a*b)
print('')
a = np.ceil(10*np.random.randn(3,1))
b= np.ceil(10*np.random.randn(1,3))
print(a)
print(b)
print(a*b)
print('')
print('================')
print('================')
print('a.dot(b)')
print('')
a = np.ceil(10*np.random.randn(3,))
b= np.ceil(10*np.random.randn(3,))
print(a)
print(b)
print(a.dot(b))
print('')
a = np.ceil(10*np.random.randn(3,1))
b= np.ceil(10*np.random.randn(3,1))
print(a)
print(b)
# print(a.dot(b))
print("# ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)")
print('')
a = np.ceil(10*np.random.randn(1,3))
b= np.ceil(10*np.random.randn(3,1))
print(a)
print(b)
print(a.dot(b))
print('')
a = np.ceil(10*np.random.randn(3,1))
b= np.ceil(10*np.random.randn(1,3))
print(a)
print(b)
print(a.dot(b))
print('')
print('================')
print('================')
print('a@b')
print('')
a = np.ceil(10*np.random.randn(3,))
b= np.ceil(10*np.random.randn(3,))
print(a)
print(b)
print(a@b)
print('')
a = np.ceil(10*np.random.randn(3,1))
b= np.ceil(10*np.random.randn(3,1))
print(a)
print(b)
# print(a@b)
print("matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)")
print('')
a = np.ceil(10*np.random.randn(1,3))
b= np.ceil(10*np.random.randn(3,1))
print(a)
print(b)
print(a@b)
print('')
a = np.ceil(10*np.random.randn(3,1))
b= np.ceil(10*np.random.randn(1,3))
print(a)
print(b)
print(a@b) 
print('')
print('================')

a*b

[ -7. -11.  -7.]
[ -4. -26. -21.]
[ 28. 286. 147.]

[[-12.]
 [-11.]
 [-20.]]
[[ -2.]
 [-14.]
 [  4.]]
[[ 24.]
 [154.]
 [-80.]]

[[ 2. -8. -7.]]
[[10.]
 [14.]
 [15.]]
[[  20.  -80.  -70.]
 [  28. -112.  -98.]
 [  30. -120. -105.]]

[[-14.]
 [  3.]
 [  5.]]
[[  1. -20.  -9.]]
[[ -14.  280.  126.]
 [   3.  -60.  -27.]
 [   5. -100.  -45.]]

a.dot(b)

[-5.  2. -8.]
[-4. 19.  6.]
10.0

[[ 7.]
 [-1.]
 [ 5.]]
[[ 9.]
 [ 8.]
 [21.]]
# ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

[[  2. -12.   3.]]
[[-4.]
 [14.]
 [12.]]
[[-140.]]

[[7.]
 [4.]
 [3.]]
[[ 5. -3. 11.]]
[[ 35. -21.  77.]
 [ 20. -12.  44.]
 [ 15.  -9.  33.]]

a@b

[ 2. -5.  2.]
[ 13. -14.  -3.]
90.0

[[-18.]
 [ 17.]
 [ -6.]]
[[ -5.]
 [-24.]
 [ 18.]]
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

[[-13.  -0.   5.]]
[[-0.]
 [-8.]
 [-9.]]
[[-45.]]

[[-3.]
 [ 7.]
 [-1.]]
[[ 7. -1. -3.]]
[[-21.   3.   9.]
 [ 49.  -7. 

# Matrix-Matrix and Matrix-Array Multiplication

In [23]:
print('================')
print('a*b')
print('')
a = np.ceil(10*np.random.randn(3,2))
b= np.ceil(10*np.random.randn(3,2))
print(a)
print(b)
print(a*b)
print('')
a = np.ceil(10*np.random.randn(3,2))
b= np.ceil(10*np.random.randn(2,3))
print(a)
print(b)
# print(a*b)
print("ValueError: operands could not be broadcast together with shapes (3,2) (2,3)")
print('')
a = np.ceil(10*np.random.randn(2,3))
b= np.ceil(10*np.random.randn(2,3))
print(a)
print(b)
print(a*b)
print('')
a = np.ceil(10*np.random.randn(3,2))
b= np.ceil(10*np.random.randn(3,1))
print(a)
print(b)
print(a*b)
print('')
a = np.ceil(10*np.random.randn(2,3))
b= np.ceil(10*np.random.randn(1,3))
print(a)
print(b)
print(a*b)
print('')
print('================')
print('================')
print('a.dot(b)')
print('')
a = np.ceil(10*np.random.randn(3,2))
b= np.ceil(10*np.random.randn(3,2))
print(a)
print(b)
# print(a.dot(b))
print("ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)")
print('')
a = np.ceil(10*np.random.randn(3,2))
b= np.ceil(10*np.random.randn(2,3))
print(a)
print(b)
print(a.dot(b))
print('')
a = np.ceil(10*np.random.randn(2,3))
b= np.ceil(10*np.random.randn(2,3))
print(a)
print(b)
# print(a.dot(b))
print("ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)")
print('')
a = np.ceil(10*np.random.randn(3,2))
b= np.ceil(10*np.random.randn(3,1))
print(a)
print(b)
# print(a.dot(b))
print("ValueError: shapes (3,2) and (3,1) not aligned: 2 (dim 1) != 3 (dim 0)")
print('')
a = np.ceil(10*np.random.randn(3,1))
b= np.ceil(10*np.random.randn(1,3))
print(a)
print(b)
print(a.dot(b))
print('')
print('================')
print('================')
print('a@b')
print('')
a = np.ceil(10*np.random.randn(3,2))
b= np.ceil(10*np.random.randn(3,2))
print(a)
print(b)
# print(a@b)
print("ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)")
print('')
a = np.ceil(10*np.random.randn(3,2))
b= np.ceil(10*np.random.randn(2,3))
print(a)
print(b)
print(a@b)
print('')
a = np.ceil(10*np.random.randn(2,3))
b= np.ceil(10*np.random.randn(1,3))
print(a)
print(b)
# print(a@b)
print("ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)")
print('')
a = np.ceil(10*np.random.randn(3,2))
b= np.ceil(10*np.random.randn(3,1))
print(a)
print(b)
# print(a@b)
print("ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)")
print('')
a = np.ceil(10*np.random.randn(2,3))
b= np.ceil(10*np.random.randn(1,3))
print(a)
print(b)
# print(a@b) 
print("ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)")
print('')
print('================')

a*b

[[-13.  -3.]
 [ -4.  -9.]
 [ -1.  -2.]]
[[ 4. -8.]
 [22. -6.]
 [12. -5.]]
[[-52.  24.]
 [-88.  54.]
 [-12.  10.]]

[[12.  6.]
 [-5. 15.]
 [25. 11.]]
[[ 7. -6.  4.]
 [-0. 10. -4.]]
ValueError: operands could not be broadcast together with shapes (3,2) (2,3)

[[12. -4.  8.]
 [-2.  7. 15.]]
[[10. 10.  8.]
 [ 4. -8.  6.]]
[[120. -40.  64.]
 [ -8. -56.  90.]]

[[-19.   5.]
 [ -7.   5.]
 [  2.   3.]]
[[-3.]
 [-3.]
 [13.]]
[[ 57. -15.]
 [ 21. -15.]
 [ 26.  39.]]

[[-11.   2.  -1.]
 [  4. -16.  10.]]
[[-2. -6. 15.]]
[[ 22. -12. -15.]
 [ -8.  96. 150.]]

a.dot(b)

[[ 16.  -3.]
 [  7. -12.]
 [  5.  18.]]
[[-7.  5.]
 [-6.  4.]
 [-2. -1.]]
ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

[[-12.  -2.]
 [ -3.  -1.]
 [ -2.  -3.]]
[[  5.  22.   8.]
 [ -1.   3. -10.]]
[[ -58. -270.  -76.]
 [ -14.  -69.  -14.]
 [  -7.  -53.   14.]]

[[  4.   3. -23.]
 [-13.  -9.  -6.]]
[[-2. 11. -2.]
 [-4. 12. -4.]]
ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

[[ -3